name: 'Get & Cache Dependecies'
descriptions: 'Get the dependecies (via npm) and cache them'
inputs:
  caching: 
    description: 'Wether to cache dependencies or not'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules # cache the node modules instead of npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true' # if no cache then run npm ci
      run: npm ci
      shell: bash # when to run the command above
