
# just the workflow name
name: Hello World

# on is when to activate the workflow, there is many ways of trigger it
on: workflow_dispatch

# workflow -> job -> steps for each job
# the name of each job is up to us
jobs:
  first-job: 
    # the first thing is add the environment on which we want to run our steps
    # this is basically the runner
    # available runners -> docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-latest
    steps:
      # the name of the step
      - name: Print something
      # run is the command that should be executed 
      # we can use run (for simple commands) or github action for more complex and repeated things
        run: echo "Hello World!"
      - name: Print something again
        run: echo "Goodbye"
  
  second-job:
    runs-on: ubuntu-latest
    steps:
      # 
      - name: Print something
      # run multitple commands syntax
        run: |
            echo "1"
            echo "2"
            echo "3"
  
