name: Just The Workflow Name

# on is when to activate the workflow, there is many ways of trigger it
on: workflow_dispatch

# workflow -> job -> steps for each job
# the name of each job is up to us
jobs:
  first-job: 
    # the first thing is add the environment on which we want to run our steps
    # this is basically the runner
    # available runners -> docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-latest
    steps:
      # the name of the step
      - name: Print something
      # run is the command that should be executed 
        run: echo "Hello World!"
      - name: Print something again
        run: echo "Goodbye"
  

  
