name: Section-2
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        # this syntaxt is called "expression"
        run: echo "${{ toJSON(github.event) }}" # access to metadata available from github - env variables for example